"""Shared application constants grouped by domain."""

from .tuning import (
    DEFAULT_CONTEXT_SUMMARY_CAP_RATIO,
    DEFAULT_CONTEXT_SUMMARY_FULL_GROWTH_UNITS,
    DEFAULT_CONTEXT_SUMMARY_INITIAL_RATIO,
    DEFAULT_CONTEXT_TARGET_RATIO,
    DEFAULT_CONTEXT_TRIGGER_RATIO,
    DEFAULT_TOOL_RESULT_MAX_CHARS,
)
from .paths import (
    DATA_DIR_NAME,
    DEFAULT_LOG_FILE,
    DEFAULT_SESSION_NAME,
    LOG_DIR_NAME,
    MEMORY_DIR_NAME,
    MEMORY_FILE_NAME,
    SESSION_FILE_NAME,
    USER_MEMORY_FILE_NAME,
    USER_CONFIG_FILE_NAME,
    WORKSPACE_METADATA_FILE_NAME,
)


__all__ = [
    "DEFAULT_CONTEXT_SUMMARY_CAP_RATIO",
    "DEFAULT_CONTEXT_SUMMARY_FULL_GROWTH_UNITS",
    "DEFAULT_CONTEXT_SUMMARY_INITIAL_RATIO",
    "DEFAULT_CONTEXT_TARGET_RATIO",
    "DEFAULT_CONTEXT_TRIGGER_RATIO",
    "DEFAULT_LOG_FILE",
    "DEFAULT_SESSION_NAME",
    "DEFAULT_TOOL_RESULT_MAX_CHARS",
    "DATA_DIR_NAME",
    "LOG_DIR_NAME",
    "MEMORY_DIR_NAME",
    "MEMORY_FILE_NAME",
    "SESSION_FILE_NAME",
    "USER_MEMORY_FILE_NAME",
    "USER_CONFIG_FILE_NAME",
    "WORKSPACE_METADATA_FILE_NAME",
]
