"""Constants for runtime tuning policies."""

DEFAULT_CONTEXT_TRIGGER_RATIO = 0.8
DEFAULT_CONTEXT_TARGET_RATIO = 0.2
DEFAULT_CONTEXT_SUMMARY_INITIAL_RATIO = 0.1
DEFAULT_CONTEXT_SUMMARY_CAP_RATIO = 0.2
DEFAULT_CONTEXT_SUMMARY_FULL_GROWTH_UNITS = 10.0
DEFAULT_TOOL_RESULT_MAX_CHARS = 40_000
